/**
 * BlueHop
 * HackNYU is a collaborative platform to build ideas into reality
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface AccountParam {
    nickname?: string;

    picture?: string;

    email?: string;

    name: string;

}
